'use client';

import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { PageHeader } from '@/components/layout/PageHeader';
import { StatusBadge } from '@/components/ui/StatusBadge';
import type { IntelligenceBrief } from '@/lib/types/database';

export default function BriefPage() {
  const [briefs, setBriefs] = useState<IntelligenceBrief[]>([]);
  const [selectedBrief, setSelectedBrief] = useState<IntelligenceBrief | null>(null);

  useEffect(() => {
    const supabase = createClient();
    async function load() {
      const { data } = await supabase
        .from('intelligence_briefs')
        .select('*')
        .order('brief_date', { ascending: false });
      const briefList = (data as IntelligenceBrief[]) || [];
      setBriefs(briefList);
      if (briefList.length > 0) setSelectedBrief(briefList[0]);
    }
    load();
  }, []);

  return (
    <div className="pt-2 md:pt-0">
      <PageHeader
        title="Daily Intelligence Brief"
        subtitle="AI-generated strategic intelligence summary"
        action={
          <button
            className="px-4 py-2 rounded-lg text-sm font-medium text-white"
            style={{ background: 'var(--navy)' }}
            onClick={() => alert('Brief generation requires Claude API key. Add ANTHROPIC_API_KEY to .env.local to enable.')}
          >
            Generate New Brief
          </button>
        }
      />

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Brief History Sidebar */}
        <div className="lg:col-span-1">
          <div className="rounded-xl border p-4" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
            <h3 className="text-sm font-semibold mb-3" style={{ color: 'var(--navy)' }}>Brief History</h3>
            <div className="space-y-2">
              {briefs.map((brief) => (
                <button
                  key={brief.id}
                  onClick={() => setSelectedBrief(brief)}
                  className="w-full text-left px-3 py-2 rounded-lg text-sm transition-colors"
                  style={{
                    background: selectedBrief?.id === brief.id ? 'var(--navy)' : 'transparent',
                    color: selectedBrief?.id === brief.id ? '#ffffff' : 'var(--text-primary)',
                  }}
                >
                  {new Date(brief.brief_date).toLocaleDateString('en-US', {
                    weekday: 'short',
                    month: 'short',
                    day: 'numeric',
                  })}
                  <p className="text-xs mt-0.5" style={{ color: selectedBrief?.id === brief.id ? 'var(--text-sidebar)' : 'var(--text-secondary)' }}>
                    Generated by {brief.generated_by}
                  </p>
                </button>
              ))}
              {briefs.length === 0 && (
                <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>No briefs generated yet.</p>
              )}
            </div>
          </div>
        </div>

        {/* Brief Content */}
        <div className="lg:col-span-3">
          {selectedBrief ? (
            <div>
              {/* Highlights */}
              {selectedBrief.highlights && (
                <div className="rounded-xl border p-5 mb-6" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
                  <h3 className="text-sm font-semibold mb-3" style={{ color: 'var(--navy)' }}>Key Highlights</h3>
                  <div className="space-y-2">
                    {(selectedBrief.highlights as { text: string; priority: string }[]).map((h, i) => (
                      <div key={i} className="flex items-start gap-2">
                        <StatusBadge status={h.priority} />
                        <p className="text-sm">{h.text}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Federal Summary */}
              {selectedBrief.federal_highlights && (
                <div className="rounded-xl border p-5 mb-6" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
                  <h3 className="text-sm font-semibold mb-3" style={{ color: 'var(--navy)' }}>Federal Pipeline Summary</h3>
                  <div className="grid grid-cols-2 md:grid-cols-5 gap-4 text-center">
                    {(() => {
                      const fh = selectedBrief.federal_highlights as Record<string, number | string>;
                      return (
                        <>
                          <div>
                            <p className="text-xl font-bold" style={{ color: 'var(--navy)' }}>{fh.total_opportunities}</p>
                            <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>Total Opps</p>
                          </div>
                          <div>
                            <p className="text-xl font-bold" style={{ color: 'var(--success)' }}>{fh.high_fit_count}</p>
                            <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>High Fit</p>
                          </div>
                          <div>
                            <p className="text-xl font-bold" style={{ color: 'var(--navy)' }}>${((fh.total_pipeline_value as number) / 1000000).toFixed(1)}M</p>
                            <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>Pipeline</p>
                          </div>
                          <div>
                            <p className="text-xl font-bold" style={{ color: 'var(--navy)' }}>{fh.sdvosb_opportunities}</p>
                            <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>SDVOSB</p>
                          </div>
                          <div>
                            <p className="text-xl font-bold" style={{ color: 'var(--warning)' }}>
                              {fh.nearest_deadline ? new Date(fh.nearest_deadline as string).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) : 'N/A'}
                            </p>
                            <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>Next Deadline</p>
                          </div>
                        </>
                      );
                    })()}
                  </div>
                </div>
              )}

              {/* Competitor Mentions */}
              {selectedBrief.competitor_mentions && (
                <div className="rounded-xl border p-5 mb-6" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
                  <h3 className="text-sm font-semibold mb-3" style={{ color: 'var(--navy)' }}>Competitor Mentions</h3>
                  <div className="flex flex-wrap gap-3">
                    {Object.entries(selectedBrief.competitor_mentions as Record<string, number>)
                      .sort(([, a], [, b]) => b - a)
                      .map(([name, count]) => (
                        <div key={name} className="flex items-center gap-2 px-3 py-1.5 rounded-lg" style={{ background: 'var(--bg-primary)' }}>
                          <span className="text-sm font-medium">{name}</span>
                          <span className="text-xs font-bold px-1.5 py-0.5 rounded" style={{ background: 'var(--navy)', color: '#ffffff' }}>
                            {count}
                          </span>
                        </div>
                      ))}
                  </div>
                </div>
              )}

              {/* Full Brief */}
              <div className="rounded-xl border p-5" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
                <h3 className="text-sm font-semibold mb-3" style={{ color: 'var(--navy)' }}>Full Brief</h3>
                <div
                  className="prose prose-sm max-w-none"
                  style={{ color: 'var(--text-primary)' }}
                >
                  {selectedBrief.content.split('\n').map((line, i) => {
                    if (line.startsWith('# ')) return <h1 key={i} className="text-xl font-bold mt-6 mb-3" style={{ color: 'var(--navy)' }}>{line.slice(2)}</h1>;
                    if (line.startsWith('## ')) return <h2 key={i} className="text-lg font-semibold mt-5 mb-2" style={{ color: 'var(--navy)' }}>{line.slice(3)}</h2>;
                    if (line.startsWith('**') && line.endsWith('**')) return <p key={i} className="font-semibold mt-3 mb-1">{line.slice(2, -2)}</p>;
                    if (line.startsWith('---')) return <hr key={i} className="my-4" style={{ borderColor: 'var(--border)' }} />;
                    if (line.startsWith('|')) return <p key={i} className="text-sm font-mono" style={{ color: 'var(--text-secondary)' }}>{line}</p>;
                    if (line.trim() === '') return <br key={i} />;
                    return <p key={i} className="text-sm leading-relaxed mb-1">{line}</p>;
                  })}
                </div>
              </div>
            </div>
          ) : (
            <div className="rounded-xl border p-16 text-center" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
              <p className="text-lg font-semibold mb-2" style={{ color: 'var(--navy)' }}>No Brief Selected</p>
              <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                Generate a new brief or select one from the history.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
